// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  agentId: __t.u64().name("agent_id"),
  actionType: __t.string().name("action_type"),
  description: __t.string(),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  createdAt: __t.timestamp().name("created_at"),
});
