// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerWallet: __t.string().name("owner_wallet"),
  name: __t.string(),
  valuesProfile: __t.string().name("values_profile"),
  configJson: __t.string().name("config_json"),
  riskTolerance: __t.string().name("risk_tolerance"),
  isActive: __t.bool().name("is_active"),
  privyWalletId: __t.option(__t.string()).name("privy_wallet_id"),
  privyWalletAddress: __t.option(__t.string()).name("privy_wallet_address"),
  totalVotes: __t.u32().name("total_votes"),
  accuracyScore: __t.u32().name("accuracy_score"),
  delegationCount: __t.u32().name("delegation_count"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
