// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  delegatorWallet: __t.string().name("delegator_wallet"),
  agentId: __t.u64().name("agent_id"),
  realmAddress: __t.string().name("realm_address"),
  scopeBitmap: __t.u64().name("scope_bitmap"),
  isActive: __t.bool().name("is_active"),
  onChainPda: __t.option(__t.string()).name("on_chain_pda"),
  createdAt: __t.timestamp().name("created_at"),
});
