// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivityLog = __t.object("ActivityLog", {
  id: __t.u64(),
  agentId: __t.u64(),
  actionType: __t.string(),
  description: __t.string(),
  metadataJson: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ActivityLog = __Infer<typeof ActivityLog>;

export const Agents = __t.object("Agents", {
  id: __t.u64(),
  ownerWallet: __t.string(),
  name: __t.string(),
  valuesProfile: __t.string(),
  configJson: __t.string(),
  riskTolerance: __t.string(),
  isActive: __t.bool(),
  privyWalletId: __t.option(__t.string()),
  privyWalletAddress: __t.option(__t.string()),
  totalVotes: __t.u32(),
  accuracyScore: __t.u32(),
  delegationCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Agents = __Infer<typeof Agents>;

export const AiAnalyses = __t.object("AiAnalyses", {
  id: __t.u64(),
  analysisKey: __t.string(),
  agentId: __t.u64(),
  proposalAddress: __t.string(),
  analysisJson: __t.string(),
  recommendation: __t.string(),
  confidence: __t.f64(),
  createdAt: __t.timestamp(),
});
export type AiAnalyses = __Infer<typeof AiAnalyses>;

export const Delegations = __t.object("Delegations", {
  id: __t.u64(),
  delegatorWallet: __t.string(),
  agentId: __t.u64(),
  realmAddress: __t.string(),
  scopeBitmap: __t.u64(),
  isActive: __t.bool(),
  onChainPda: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Delegations = __Infer<typeof Delegations>;

export const TrackedRealms = __t.object("TrackedRealms", {
  id: __t.u64(),
  address: __t.string(),
  name: __t.string(),
  isActive: __t.bool(),
  addedAt: __t.timestamp(),
});
export type TrackedRealms = __Infer<typeof TrackedRealms>;

export const Votes = __t.object("Votes", {
  id: __t.u64(),
  voteKey: __t.string(),
  agentId: __t.u64(),
  proposalAddress: __t.string(),
  vote: __t.string(),
  reasoning: __t.string(),
  confidence: __t.f64(),
  txSignature: __t.option(__t.string()),
  tapestryContentId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Votes = __Infer<typeof Votes>;

