// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  voteKey: __t.string().name("vote_key"),
  agentId: __t.u64().name("agent_id"),
  proposalAddress: __t.string().name("proposal_address"),
  vote: __t.string(),
  reasoning: __t.string(),
  confidence: __t.f64(),
  txSignature: __t.option(__t.string()).name("tx_signature"),
  tapestryContentId: __t.option(__t.string()).name("tapestry_content_id"),
  createdAt: __t.timestamp().name("created_at"),
});
