// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateAgentReducer from "../create_agent_reducer";
import UpdateAgentReducer from "../update_agent_reducer";
import RecordVoteReducer from "../record_vote_reducer";
import CreateDelegationReducer from "../create_delegation_reducer";
import RevokeDelegationReducer from "../revoke_delegation_reducer";
import StoreAiAnalysisReducer from "../store_ai_analysis_reducer";
import AddTrackedRealmReducer from "../add_tracked_realm_reducer";
import RemoveTrackedRealmReducer from "../remove_tracked_realm_reducer";
import SeedTrackedRealmsReducer from "../seed_tracked_realms_reducer";

export type CreateAgentParams = __Infer<typeof CreateAgentReducer>;
export type UpdateAgentParams = __Infer<typeof UpdateAgentReducer>;
export type RecordVoteParams = __Infer<typeof RecordVoteReducer>;
export type CreateDelegationParams = __Infer<typeof CreateDelegationReducer>;
export type RevokeDelegationParams = __Infer<typeof RevokeDelegationReducer>;
export type StoreAiAnalysisParams = __Infer<typeof StoreAiAnalysisReducer>;
export type AddTrackedRealmParams = __Infer<typeof AddTrackedRealmReducer>;
export type RemoveTrackedRealmParams = __Infer<typeof RemoveTrackedRealmReducer>;
export type SeedTrackedRealmsParams = __Infer<typeof SeedTrackedRealmsReducer>;

